---

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - binfmt-support
      - apparmor-utils
      - python3-requests
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
