---

- name: Add docker.io apt-key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
  become: true

- name: Add docker.io repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: /etc/apt/trusted.gpg.d/docker.asc
    state: present
    enabled: true
  become: true

- name: Find legacy docker.io .list repository files
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: '*.list'
    contains: '.*download\.docker\.com.*'
  register: legacy_docker_repos
  become: true

- name: Remove legacy docker.io .list repository files
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ legacy_docker_repos.files }}'
  loop_control:
    label: '{{ item.path }}'
  become: true

- name: Install docker-ce
  ansible.builtin.apt:
    name:
      - docker-ce{{ dockerd_apt_version | default('') }}
      - docker-ce-cli{{ dockerd_apt_version | default('') }}
      - containerd.io
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Add users to docker group
  ansible.builtin.user:
    name: '{{ item }}'
    groups: docker
    append: true
  with_items: '{{ dockerd_users }}'
  when: dockerd_users is defined
  become: true
