---

- name: Stat /proc/sys/vm/max_map_count
  ansible.builtin.stat:
    path: /proc/sys/vm/max_map_count
  register: stat_vm_max_map_count
  become: true

- name: Increase vm.max_map_count
  ansible.posix.sysctl:
    name: "vm.max_map_count"
    value: "262144"
    sysctl_set: true
    state: present
    reload: true
  become: true
  when:
    - stat_vm_max_map_count.stat.exists
    - stat_vm_max_map_count.stat.writeable

- name: Add br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present
  become: true

- name: Add users to docker group
  ansible.builtin.user:
    name: '{{ item }}'
    groups: docker
    append: yes
  with_items: '{{ dockerd_users }}'
  when: dockerd_users is defined
  become: true
