---

version: 2.1

jobs:

  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: default
    resource_class: large
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: ls -lh /etc/apt/sources.list.d/
      - run: sudo rm -f /etc/apt/sources.list.d/google.list /etc/apt/sources.list.d/heroku.list /etc/apt/sources.list.d/docker.list
      - run: sudo apt-get update
      - run: sudo apt remove --assume-yes --purge apparmor
      - run: sudo apt install --assume-yes ansible ansible-lint

      - run: ansible --version
      - run: ansible-lint --version

      - checkout

      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-lint

      - run:
          command: ansible-playbook tests/test.yml -i tests/inventory --connection=local
          no_output_timeout: 30m

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
